"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, Bookmark, BookmarkCheck, Check, ChevronDown, CircleDollarSign, GitCompare, Heart, Layers3, Plus, RefreshCw, RotateCcw, ShoppingBag, ShoppingCart, Star, Target, TrendingDown, Wallet, Wand2, X, Crown } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Product={id:string;category_id:string|null;name:string;slug:string;short_description:string|null;description:string|null;price:number;original_price:number|null;stock:number;image_url:string|null;brand:string|null;rating:number;reviews_count:number;is_featured:boolean;is_flash_sale:boolean;is_active:boolean};
type Category={id:string;name:string;slug:string};
type Goal="value"|"quality"|"premium"|"multiple";

const goals=[
 {id:"value" as Goal,title:"Maximum Value",desc:"Best products for every rupee",icon:TrendingDown},
 {id:"quality" as Goal,title:"Quality First",desc:"Prioritize ratings and reliability",icon:BadgeCheck},
 {id:"premium" as Goal,title:"Premium",desc:"Higher-end products within budget",icon:Crown},
 {id:"multiple" as Goal,title:"More Products",desc:"Build a complete shopping cart",icon:Layers3},
];
const budgets=[2000,5000,10000,20000,50000];
const CATEGORY_ORDER=["Mobile","Electronics","Home & Kitchen","Fashion","Footwear","Beauty","Toy & Baby","Sports & Outdoor","Appliance","Automotive","Eyewear","Books","Gaming","Watch","Bag"];
const CATEGORY_ALIASES:Record<string,string[]>={
  mobile:["mobile","mobile phones","mobiles"], electronics:["electronics","electronic"], "home & kitchen":["home & kitchen","home kitchen","home and kitchen","home-kitchen"], fashion:["fashion"], footwear:["footwear","shoes"], beauty:["beauty"], "toy & baby":["toy & baby","toys & baby","toy baby","toys baby"], sports:["sports","sports & outdoor","sports outdoor"], appliance:["appliance","appliances"], automotive:["automotive","auto","car & bike"], eyewear:["eyewear","eye wear"], books:["books","book"], gaming:["gaming","games"], watch:["watch","watches"], bag:["bag","bags"]
};
const SUB:Record<string,string[]>= {
 fashion:["T-Shirts","Shirts","Tops","Jeans","Trousers & Pants","Dresses","Skirts","Jackets & Coats","Hoodies & Sweatshirts","Ethnic Wear","Innerwear","Sleepwear","Sportswear","Fashion Accessories"],
 mobile:["Smartphones","Cases & Covers","Chargers & Adapters","Power Banks","Screen Protectors","Cables","Mobile Holders","Mobile Accessories"],
 electronics:["Headphones & Earbuds","Speakers","Keyboards","Mice","Monitors","Cameras","Printers","Projectors","Networking","Computer Accessories"],
 "home & kitchen":["Kitchen Essentials","Cookware","Coffee & Tea","Dining & Serveware","Home Decor","Storage & Organization","Furniture","Bedding & Bath","Cleaning"],
 appliance:["Kitchen Appliances","Refrigerators","Washing Machines","Air Conditioners","Fans","Coolers","Vacuum Cleaners","Geysers & Water Heaters","Irons"],
 footwear:["Sneakers","Running Shoes","Sports Shoes","Casual Shoes","Formal Shoes","Sandals","Slippers","Boots","Heels","Kids Footwear"],
 beauty:["Face Care","Serums","Moisturizers","Sunscreen","Makeup","Lip Makeup","Eye Makeup","Foundation & Concealer","Hair Care","Hair Styling","Fragrance","Bath & Body","Oral Care","Men's Grooming","Beauty Tools","Nail Care"],
 "toy & baby":["Toys","Board Games","Puzzles","Educational Toys","Baby Care","Baby Clothing","Baby Feeding","Kids Games","Remote Control Toys","Outdoor Toys"],
 sports:["Fitness & Gym","Running","Yoga","Sportswear","Cricket","Football","Badminton","Cycling","Camping & Outdoor","Sports Accessories"],
 automotive:["Car Accessories","Bike Accessories","Car Electronics","Cleaning & Care","Interior Accessories","Exterior Accessories","Tools & Maintenance","Safety Accessories"],
 gaming:["Gaming Keyboards","Gaming Mice","Gaming Headsets","Controllers","Consoles","Gaming Monitors","Gaming Chairs","Gaming Accessories","PC Gaming"],
 watch:["Smartwatches","Analog Watches","Digital Watches","Sports Watches","Luxury Watches","Watch Accessories"],
 bag:["Backpacks","Handbags","Sling Bags","Travel Bags","Laptop Bags","School Bags","Wallets","Clutches"],
 books:["Study & Academic","Competitive Exams","Fiction","Non-Fiction","Self Help","Business & Finance","Children's Books","Comics & Graphic Novels"],
 eyewear:["Sunglasses","Eyeglasses","Blue Light Glasses","Reading Glasses","Kids Eyewear","Eyewear Accessories"]
};
function norm(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function categoryKey(c:Category|null){if(!c)return "";const n=norm(c.name),s=norm(c.slug);return Object.keys(CATEGORY_ALIASES).find(k=>CATEGORY_ALIASES[k].some(a=>n===norm(a)||s===norm(a)||n.includes(norm(a))))||""}
function subs(c:Category|null){const k=categoryKey(c);return k?SUB[k]||[]:[]}
function matchSub(p:Product,s:string){
  if(!s)return true;
  const h=norm([p.name,p.brand,p.slug,p.short_description,p.description].filter(Boolean).join(" "));
  const n=norm(s);
  const aliases:Record<string,string[]>= {
    "t shirts":["t shirt","tshirts","tee","tees"], "trousers pants":["trousers","pants"], "home decor":["home decor","decor"],
    "storage organization":["storage","organization","organizer"], "hair care":["hair care","shampoo","conditioner"], "hair styling":["hair styling","styler","hair dryer"],
    "car accessories":["car accessory","car accessories"], "bike accessories":["bike accessory","bike accessories","motorcycle"], "computer accessories":["computer accessory","computer accessories","pc accessory"],
    "watch accessories":["watch accessory","watch accessories"], "laptop bags":["laptop bag","laptop bags"], "competitive exams":["competitive exam","exam prep"],
    "blue light glasses":["blue light","computer glasses"]
  };
  if(h.includes(n))return true;
  const a=aliases[n]||[];
  return a.some(x=>h.includes(norm(x)))||n.split(" ").filter(x=>x.length>2).every(x=>h.includes(x));
}
function score(p:Product,b:number,g:Goal){let x=0,u=p.price/Math.max(b,1);x+=u<=.15?18:u<=.3?25:u<=.5?28:u<=.75?24:u<=1?17:4;x+=Math.min(28,Math.round(p.rating/5*28));x+=Math.min(15,Math.round(p.reviews_count/15));if(p.is_featured)x+=8;if(p.is_flash_sale)x+=8;const d=p.original_price&&p.original_price>p.price?Math.round((p.original_price-p.price)/p.original_price*100):0;if(g==="value")x+=Math.min(13,d);if(g==="quality")x+=p.rating>=4.5?12:p.rating>=4?7:0;if(g==="premium")x+=(p.price>=b*.4?8:0)+(p.rating>=4.5?7:0);if(g==="multiple")x+=p.price<=b*.25?12:p.price<=b*.4?7:0;return Math.max(0,Math.min(99,x-(p.stock<=0?30:0)))}
function money(v:number){return `₹${Number(v||0).toLocaleString("en-IN")}`}
function discount(p:Product){return p.original_price&&p.original_price>p.price?Math.round((p.original_price-p.price)/p.original_price*100):0}
function Img({p}:{p:Product}){const [i,setI]=useState(0);const c=p.image_url?.replace(/^\/+/,"")||"";const a=c?[`/${c}`,`/products/${c}`,`/product-images/${c}`,`/images/products/${c}`]:[];return a[i]?<img src={a[i]} alt={p.name} className="h-full w-full object-contain p-4" onError={()=>setI(i+1)}/>:<div className="flex h-full items-center justify-center text-[#b9aa91]"><ShoppingBag/></div>}

export default function BudgetBuilderPage(){
 const supabase=createClient();
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[wishlist,setWishlist]=useState<string[]>([]),[cart,setCart]=useState<Record<string,number>>({});
 const [loading,setLoading]=useState(true),[building,setBuilding]=useState(false),[ready,setReady]=useState(false),[budget,setBudget]=useState(10000),[custom,setCustom]=useState("10000"),[goal,setGoal]=useState<Goal>("value"),[categoryId,setCategoryId]=useState(""),[subcategory,setSubcategory]=useState(""),[seed,setSeed]=useState(1),[manual,setManual]=useState(false),[selected,setSelected]=useState<string[]>([]),[previous,setPrevious]=useState<string[]>([]),[swap,setSwap]=useState<string|null>(null),[compare,setCompare]=useState<string[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState<string|null>(null),[saved,setSaved]=useState(false),[search,setSearch]=useState("");
 const notify=(x:string)=>{setNotice(x);setTimeout(()=>setNotice(""),2600)};
 useEffect(()=>{load();try{const x=JSON.parse(localStorage.getItem("primecart-budget-plan")||"null");if(x){setBudget(Number(x.budget)||10000);setCustom(String(Number(x.budget)||10000));setGoal(x.goal||"value");setCategoryId(x.categoryId||"");setSubcategory(x.subcategory||"");setSelected(Array.isArray(x.productIds)?x.productIds:[]);setManual(true);setReady(true);setSaved(true)}}catch{}},[]);
 async function load(){setLoading(true);try{const {data:{user},error:a}=await supabase.auth.getUser();if(a)throw a;if(!user){location.href="/auth/login?redirect=/dashboard/budget-builder";return}const [p,c,w,ci]=await Promise.all([supabase.from("products").select("id,category_id,name,slug,short_description,description,price,original_price,stock,image_url,brand,rating,reviews_count,is_featured,is_flash_sale,is_active").eq("is_active",true),supabase.from("categories").select("id,name,slug").order("name"),supabase.from("wishlist_items").select("product_id").eq("user_id",user.id),supabase.from("cart_items").select("product_id,quantity").eq("user_id",user.id)]);if(p.error)throw p.error;if(c.error)throw c.error;if(w.error)throw w.error;if(ci.error)throw ci.error;setProducts((p.data||[]) as Product[]);setCategories((c.data||[]) as Category[]);setWishlist((w.data||[]).map(x=>String(x.product_id)));const q:Record<string,number>={};(ci.data||[]).forEach(x=>q[String(x.product_id)]=Number(x.quantity||1));setCart(q)}catch(e){console.error(e);notify("Unable to load Budget Builder data.")}finally{setLoading(false)}}
 const cat=useMemo(()=>categories.find(x=>String(x.id)===String(categoryId))||null,[categories,categoryId]);
 const available=useMemo(()=>subs(cat),[cat]);
 const matching=useMemo(()=>products.filter(p=>p.is_active&&p.stock>0&&p.price>0&&(!categoryId||String(p.category_id)===String(categoryId))&&(!subcategory||matchSub(p,subcategory))&&(!search||norm([p.name,p.brand,p.slug].join(" ")).includes(norm(search)))),[products,categoryId,subcategory,search]);
 const ranked=useMemo(()=>matching.filter(p=>p.price<=budget).sort((a,b)=>score(b,budget,goal)-score(a,budget,goal)||((a.id.charCodeAt(0)+seed)%17)-((b.id.charCodeAt(0)+seed)%17)),[matching,budget,goal,seed]);
 const auto=useMemo(()=>{const pool=(ranked.filter(p=>!previous.includes(p.id)).length?ranked.filter(p=>!previous.includes(p.id)):ranked),out:Product[]=[];let total=0;const add=(p:Product)=>{if(!out.some(x=>x.id===p.id)&&total+p.price<=budget){out.push(p);total+=p.price}};let src=[...pool];if(goal==="premium")src.sort((a,b)=>b.price-a.price||b.rating-a.rating);else if(goal==="quality")src.sort((a,b)=>b.rating-a.rating||b.reviews_count-a.reviews_count);else if(goal==="multiple")src.sort((a,b)=>a.price-b.price);for(const p of src){if(out.length>=(goal==="multiple"?8:5))break;add(p)}return out},[ranked,previous,budget,goal]);
 const ids=manual?selected:auto.map(p=>p.id);
 const plan=useMemo(()=>{const out:Product[]=[];let total=0;for(const id of ids){const p=products.find(x=>x.id===id);if(!p||!p.is_active||p.stock<=0||p.price<=0)continue;if(categoryId&&String(p.category_id)!==String(categoryId))continue;if(subcategory&&!matchSub(p,subcategory))continue;if(out.some(x=>x.id===id)||total+p.price>budget)continue;out.push(p);total+=p.price}return out},[ids,products,categoryId,subcategory,budget]);
 const spend=plan.reduce((s,p)=>s+p.price,0),remain=Math.max(0,budget-spend),usage=Math.min(100,spend/budget*100),avg=plan.length?Math.round(plan.reduce((s,p)=>s+score(p,budget,goal),0)/plan.length):0;
 const suggestions=ranked.filter(p=>!plan.some(x=>x.id===p.id)&&p.price<=remain).slice(0,6);const compareProducts=compare.map(id=>products.find(p=>p.id===id)).filter(Boolean) as Product[];
 function changeBudget(v:number){v=Math.max(1,Math.round(v));setBudget(v);setCustom(String(v));setReady(false)}
 async function build(){const b=Number(custom);if(!b||b<1)return notify("Enter a valid budget.");if(!ranked.length)return notify("No matching products fit this budget.");setBudget(b);setBuilding(true);if(ready)setPrevious(plan.map(p=>p.id));setManual(false);setSelected([]);setSeed(x=>x+1);await new Promise(r=>setTimeout(r,350));setReady(true);setBuilding(false);document.getElementById("smart-plan")?.scrollIntoView({behavior:"smooth"})}
 function togglePlan(id:string){const p=products.find(x=>x.id===id);if(!p)return;setManual(true);const base=plan.map(x=>x.id);if(base.includes(id)){setSelected(base.filter(x=>x!==id));return}if(categoryId&&String(p.category_id)!==String(categoryId)||subcategory&&!matchSub(p,subcategory))return notify("Product does not match your selection.");if(spend+p.price>budget)return notify("This product exceeds your budget.");setSelected([...base,id]);setReady(true)}
 async function wish(id:string){setBusy(id);try{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/auth/login?redirect=/dashboard/budget-builder";return}if(wishlist.includes(id)){const {error}=await supabase.from("wishlist_items").delete().eq("user_id",user.id).eq("product_id",id);if(error)throw error;setWishlist(x=>x.filter(v=>v!==id))}else{const {data:e,error:ce}=await supabase.from("wishlist_items").select("id").eq("user_id",user.id).eq("product_id",id).maybeSingle();if(ce)throw ce;if(!e){const {error}=await supabase.from("wishlist_items").insert({user_id:user.id,product_id:id});if(error)throw error}setWishlist(x=>x.includes(id)?x:[...x,id])}}catch(e){console.error(e);notify("Wishlist update failed.")}finally{setBusy(null)}}
 async function add(p:Product){setBusy(p.id);try{const {data:{user},error:a}=await supabase.auth.getUser();if(a)throw a;if(!user){location.href="/auth/login?redirect=/dashboard/budget-builder";return}const {data:e,error}=await supabase.from("cart_items").select("id,quantity").eq("user_id",user.id).eq("product_id",p.id).maybeSingle();if(error)throw error;if(e){const q=Math.min(p.stock,Math.max(1,Number(e.quantity||1)+1));const {error:u}=await supabase.from("cart_items").update({quantity:q,updated_at:new Date().toISOString()}).eq("id",e.id);if(u)throw u;setCart(x=>({...x,[p.id]:q}))}else{const {error:i}=await supabase.from("cart_items").insert({user_id:user.id,product_id:p.id,quantity:1});if(i)throw i;setCart(x=>({...x,[p.id]:1}))}dispatchEvent(new Event("cart-updated"));notify("Product added to cart.")}catch(e){console.error(e);notify("Could not add product to cart.")}finally{setBusy(null)}}
 async function addAll(){if(!plan.length)return notify("Build a plan first.");setBusy("all");try{const {data:{user},error:a}=await supabase.auth.getUser();if(a)throw a;if(!user){location.href="/auth/login?redirect=/dashboard/budget-builder";return}for(const p of plan){const {data:e,error}=await supabase.from("cart_items").select("id,quantity").eq("user_id",user.id).eq("product_id",p.id).maybeSingle();if(error)throw error;if(e){const q=Math.min(p.stock,Math.max(1,Number(e.quantity||1)+1));const {error:u}=await supabase.from("cart_items").update({quantity:q,updated_at:new Date().toISOString()}).eq("id",e.id);if(u)throw u}else{const {error:i}=await supabase.from("cart_items").insert({user_id:user.id,product_id:p.id,quantity:1});if(i)throw i}}await load();dispatchEvent(new Event("cart-updated"));notify("Complete plan added to cart.")}catch(e){console.error(e);notify("Could not add the complete plan.")}finally{setBusy(null)}}
 function save(){if(!plan.length)return notify("Build a plan first.");localStorage.setItem("primecart-budget-plan",JSON.stringify({budget,goal,categoryId,subcategory,productIds:plan.map(p=>p.id),savedAt:new Date().toISOString()}));setSaved(true);notify("Plan saved successfully.")}
 async function share(){const text=`PrimeCart Budget Plan\nBudget: ${money(budget)}\n${plan.map(p=>`• ${p.name} - ${money(p.price)}`).join("\n")}\nTotal: ${money(spend)}`;try{if(navigator.share)await navigator.share({title:"PrimeCart Budget Plan",text});else{await navigator.clipboard.writeText(text);notify("Plan copied.")}}catch{}}
 function swapProduct(oldId:string,newId:string){const p=products.find(x=>x.id===newId);if(!p)return;const total=plan.filter(x=>x.id!==oldId).reduce((s,x)=>s+x.price,0);if(total+p.price>budget)return notify("Replacement exceeds your budget.");setManual(true);setSelected([...plan.filter(x=>x.id!==oldId).map(x=>x.id),newId]);setSwap(null);setReady(true)}
 if(loading)return <main className="min-h-screen bg-[#faf8f3] p-20 text-center font-bold text-[#6f604c]">Loading Budget Builder...</main>;
 return <main className="min-h-screen bg-[#faf8f3] text-[#443729]">{notice&&<div className="fixed left-1/2 top-5 z-[100] -translate-x-1/2 rounded-full bg-[#443729] px-5 py-3 text-xs font-bold text-white shadow-xl">{notice}</div>}
 <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
 <header className="mb-7 rounded-3xl border border-[#e9dfce] bg-[#fffdf9] p-6 shadow-sm"><Link href="/dashboard" className="text-xs font-bold text-[#9b702e]">← Back to Dashboard</Link><div className="mt-4 flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#a17a3b]">Smart Shopping Planner</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">Budget Builder</h1><p className="mt-2 max-w-2xl text-sm text-[#847663]">Build a smart shopping plan without exceeding your budget.</p></div><button onClick={()=>{setBudget(10000);setCustom("10000");setGoal("value");setCategoryId("");setSubcategory("");setSelected([]);setPrevious([]);setManual(false);setReady(false)}} className="flex h-fit items-center gap-2 rounded-xl border border-[#e3d6c1] bg-white px-4 py-2.5 text-xs font-black"><RotateCcw size={14}/> Reset</button></div></header>
 <section className="rounded-3xl border border-[#e9dfce] bg-[#fffdf9] p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#f4ead7] text-[#9b702e]"><Wallet size={21}/></div><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#a27a3c]">Budget Studio</p><h2 className="text-xl font-black">Build your shopping plan</h2></div></div>
 <div className="grid gap-6 lg:grid-cols-2"><div><label className="mb-2 block text-xs font-black">Your Budget</label><div className="relative"><CircleDollarSign className="absolute left-4 top-1/2 -translate-y-1/2 text-[#a88651]" size={18}/><input value={custom} onChange={e=>setCustom(e.target.value.replace(/\D/g,""))} onBlur={()=>changeBudget(Number(custom)||1)} className="w-full rounded-2xl border border-[#dfd2bd] bg-white py-4 pl-11 text-lg font-black outline-none"/></div><div className="mt-3 flex flex-wrap gap-2">{budgets.map(x=><button key={x} onClick={()=>changeBudget(x)} className={`rounded-full border px-3 py-2 text-xs font-bold ${budget===x?"border-[#b9975b] bg-[#b9975b] text-white":"border-[#e4dac9] bg-white text-[#765b31]"}`}>{money(x)}</button>)}</div></div>
 <div><label className="mb-2 block text-xs font-black">Shopping Goal</label><div className="grid grid-cols-2 gap-2">{goals.map(g=>{const I=g.icon;return <button key={g.id} onClick={()=>{setGoal(g.id);setReady(false)}} className={`rounded-2xl border p-3 text-left ${goal===g.id?"border-[#c6a25f] bg-[#f8f0e2]":"border-[#e8dfd1] bg-white"}`}><I size={18} className="text-[#9b702e]"/><p className="mt-2 text-xs font-black">{g.title}</p><p className="mt-1 text-[10px] text-[#8b7b68]">{g.desc}</p></button>})}</div></div></div>
 <div className="mt-6 grid gap-4 md:grid-cols-3"><div><label className="mb-2 block text-xs font-black">Category</label><div className="relative"><select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setSubcategory("");setReady(false)}} className="w-full appearance-none rounded-xl border border-[#e5dac8] bg-white px-4 py-3 text-sm font-bold"><option value="">All Categories</option>{orderedCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2" size={15}/></div></div><div><label className="mb-2 block text-xs font-black">Subcategory</label><select value={subcategory} disabled={!categoryId} onChange={e=>{setSubcategory(e.target.value);setReady(false)}} className="w-full rounded-xl border border-[#e5dac8] bg-white px-4 py-3 text-sm font-bold"><option value="">All Subcategories</option>{available.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="mb-2 block text-xs font-black">Search</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Product or brand..." className="w-full rounded-xl border border-[#e5dac8] bg-white px-4 py-3 text-sm font-semibold"/></div></div>
 <div className="mt-6 flex flex-col justify-between gap-3 rounded-2xl bg-[#fbf6ed] p-4 sm:flex-row sm:items-center"><span className="text-xs font-bold text-[#786851]">{matching.length} matching · {ranked.length} within budget</span><button onClick={build} disabled={building} className="flex items-center justify-center gap-2 rounded-xl bg-[#b9975b] px-6 py-3 text-sm font-black text-white disabled:opacity-60">{building?<RefreshCw className="animate-spin" size={16}/>:<Wand2 size={16}/>} {building?"Building...":"Build Smart Plan"}<ArrowRight size={16}/></button></div></section>
 {ready&&<section id="smart-plan" className="mt-8 rounded-3xl border border-[#e9dfce] bg-[#fffdf9] p-5 shadow-sm sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-[#eee5d7] pb-6 sm:flex-row"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#a17a3b]">Smart Plan</p><h2 className="mt-1 text-2xl font-black">Your {cat?.name||"shopping"} plan</h2><p className="text-xs text-[#8b7c68]">{money(budget)} · {goals.find(x=>x.id===goal)?.title}{subcategory?` · ${subcategory}`:""}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>{setPrevious(plan.map(p=>p.id));setManual(false);setSelected([]);setSeed(x=>x+1);notify("Fresh plan generated.")}} className="rounded-xl border px-3 py-2 text-xs font-black"><RefreshCw size={13} className="mr-1 inline"/> Optimize</button><button onClick={save} className="rounded-xl border px-3 py-2 text-xs font-black">{saved?<BookmarkCheck size={13} className="mr-1 inline"/>:<Bookmark size={13} className="mr-1 inline"/>} Save</button><button onClick={share} className="rounded-xl border px-3 py-2 text-xs font-black"><GitCompare size={13} className="mr-1 inline"/> Share</button><button onClick={addAll} disabled={busy==="all"||!plan.length} className="rounded-xl bg-[#b9975b] px-4 py-2 text-xs font-black text-white">{busy==="all"?"Adding...":"Add Complete Plan"}</button></div></div>
 <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Budget",money(budget)],["Plan Value",money(spend)],["Remaining",money(remain)],["Savings",money(plan.reduce((s,p)=>s+Math.max(0,(p.original_price||p.price)-p.price),0))]].map(([a,b])=><div key={a} className="rounded-2xl border bg-[#fcfaf6] p-4"><p className="text-[10px] font-bold uppercase text-[#958674]">{a}</p><p className="mt-1 text-lg font-black">{b}</p></div>)}</div><div className="mt-5 rounded-2xl border p-4"><div className="flex justify-between text-xs font-bold"><span>Budget Allocation</span><span>{Math.round(usage)}%</span></div><div className="mt-2 h-3 rounded-full bg-[#eee6d9]"><div className="h-full rounded-full bg-[#b9975b]" style={{width:`${usage}%`}}/></div><div className="mt-4 flex justify-between text-xs font-bold"><span>Budget Health: {remain>=budget*.2?"Healthy":"Tight but safe"}</span><span>Smart Match: {avg}/99</span></div></div>
 <div className="mt-7"><h3 className="text-lg font-black">Plan Products</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{plan.map(p=><article key={p.id} className="flex gap-4 rounded-2xl border p-4"><Link href={`/dashboard/products/${p.id}`} className="h-28 w-28 shrink-0 rounded-xl bg-[#f8f4ec]"><Img p={p}/></Link><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="line-clamp-2 text-sm font-black">{p.name}</p><button onClick={()=>wish(p.id)} disabled={busy===p.id}><Heart size={18} fill={wishlist.includes(p.id)?"currentColor":"none"} className="text-[#9b702e]"/></button></div><div className="mt-1 text-[11px] text-[#887966]"><Star size={12} className="mr-1 inline" fill="currentColor"/>{p.rating.toFixed(1)} · {p.reviews_count} reviews</div><p className="mt-2 text-lg font-black">{money(p.price)}</p><div className="mt-2 flex flex-wrap justify-end gap-1.5"><button onClick={()=>setSwap(p.id)} className="rounded-lg border px-2.5 py-2 text-[10px] font-black">Change</button><button onClick={()=>setCompare(x=>x.includes(p.id)?x.filter(v=>v!==p.id):x.length<3?[...x,p.id]:x)} className="rounded-lg border px-2.5 py-2 text-[10px] font-black">Compare</button><button onClick={()=>add(p)} disabled={busy===p.id} className="rounded-lg bg-[#b9975b] px-2.5 py-2 text-[10px] font-black text-white">{busy===p.id?"Adding...":"Add to Cart"}</button></div></div></article>)}</div></div>
 {suggestions.length>0&&<div className="mt-8"><div className="flex justify-between"><div><h3 className="text-lg font-black">Remaining Suggestions</h3><p className="text-xs text-[#8c7d69]">Still within your remaining budget.</p></div><button onClick={()=>{setPrevious(plan.map(p=>p.id));setSeed(x=>x+1)}} className="text-xs font-black text-[#9b702e]">Optimize Again</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{suggestions.map(p=><div key={p.id} className="rounded-2xl border bg-[#fcfaf6] p-3"><div className="h-32 rounded-xl bg-white"><Img p={p}/></div><p className="mt-2 line-clamp-2 text-xs font-black">{p.name}</p><div className="mt-2 flex justify-between"><b>{money(p.price)}</b><button onClick={()=>togglePlan(p.id)} className="rounded-lg border px-2 py-1 text-[10px] font-black">+ Add to Plan</button></div></div>)}</div></div>}
 {compareProducts.length>=2&&<div className="mt-8 overflow-x-auto rounded-2xl border"><div className="flex justify-between border-b bg-[#fcfaf6] p-4"><h3 className="font-black">Compare</h3><button onClick={()=>setCompare([])} className="text-xs font-bold">Clear</button></div><table className="w-full min-w-[650px] text-left text-xs"><thead><tr className="border-b"><th className="p-3">Product</th><th className="p-3">Price</th><th className="p-3">Rating</th><th className="p-3">Reviews</th><th className="p-3">Discount</th><th className="p-3">Match</th></tr></thead><tbody>{compareProducts.map(p=><tr key={p.id} className="border-b"><td className="p-3 font-black">{p.name}</td><td className="p-3">{money(p.price)}</td><td className="p-3">{p.rating.toFixed(1)}</td><td className="p-3">{p.reviews_count}</td><td className="p-3">{discount(p)}%</td><td className="p-3 font-black text-[#9b702e]">{score(p,budget,goal)}/99</td></tr>)}</tbody></table></div>}
 </section>}
 <section className="mt-8 rounded-3xl border border-[#e9dfce] bg-[#fffdf9] p-5 shadow-sm sm:p-7"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#a17a3b]">Explore</p><h2 className="mt-1 text-2xl font-black">Products for your budget</h2></div>{!ranked.length?<div className="mt-6 rounded-2xl border border-dashed p-10 text-center"><ShoppingBag className="mx-auto text-[#b9975b]"/><p className="mt-2 font-black">No matching products within this budget.</p></div>:<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{ranked.slice(0,16).map(p=><article key={p.id} className="overflow-hidden rounded-2xl border bg-white"><div className="relative h-48 bg-[#f8f4ec]"><Img p={p}/><button onClick={()=>wish(p.id)} className="absolute right-3 top-3 rounded-full bg-white p-2 text-[#9b702e]"><Heart size={16} fill={wishlist.includes(p.id)?"currentColor":"none"}/></button><span className="absolute left-3 top-3 rounded-full bg-[#b9975b] px-2 py-1 text-[9px] font-black text-white">{score(p,budget,goal)}/99</span></div><div className="p-4"><Link href={`/dashboard/products/${p.id}`} className="line-clamp-2 min-h-10 text-sm font-black">{p.name}</Link><p className="mt-2 text-[10px] text-[#887966]">{p.rating.toFixed(1)} ★ · {p.reviews_count} reviews</p><div className="mt-2 flex justify-between"><b>{money(p.price)}</b><span className="text-[10px] font-bold text-emerald-700">{discount(p)}% OFF</span></div><div className="mt-3 flex gap-2"><button onClick={()=>togglePlan(p.id)} className="flex-1 rounded-xl border py-2 text-[10px] font-black">{plan.some(x=>x.id===p.id)?"In Plan":"Add to Plan"}</button><button onClick={()=>add(p)} className="flex-1 rounded-xl bg-[#b9975b] py-2 text-[10px] font-black text-white">Add to Cart</button></div></div></article>)}</div>}</section>
 <section className="my-8 rounded-3xl bg-[#443729] p-7 text-white"><h2 className="text-2xl font-black">Build smarter. Shop better.</h2><p className="mt-2 text-sm text-[#d9cfbf]">Every generated plan is checked so the total never goes above your selected budget.</p><button onClick={()=>{setReady(false);scrollTo({top:0,behavior:"smooth"})}} className="mt-5 rounded-xl bg-white px-5 py-3 text-xs font-black text-[#55432d]">Rebuild Plan</button></section>
 </div>
 {swap&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-3xl bg-[#fffdf9] p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase text-[#a17a3b]">Make the right choice</p><h2 className="text-xl font-black">Change Product</h2></div><button onClick={()=>setSwap(null)}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{ranked.filter(p=>p.id!==swap&&String(p.category_id)===String(products.find(x=>x.id===swap)?.category_id)).slice(0,6).map(p=><button key={p.id} onClick={()=>swapProduct(swap,p.id)} className="rounded-2xl border p-3 text-left"><div className="h-28 rounded-xl bg-[#f8f4ec]"><Img p={p}/></div><p className="mt-2 line-clamp-2 text-xs font-black">{p.name}</p><b className="text-sm">{money(p.price)}</b></button>)}</div></div></div>}
 </main>}
